# Generated by Django 2.1 on 2018-09-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='message_html',
        ),
    ]
