# Generated by Django 2.1 on 2018-09-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_message_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
