# Generated by Django 2.1 on 2018-09-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180919_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
