# Generated by Django 2.1 on 2018-09-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='showEveryone',
            field=models.BooleanField(null=True),
        ),
    ]
