# Generated by Django 2.1 on 2018-10-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreboard',
            options={'ordering': ['-team_score']},
        ),
    ]
