# Generated by Django 2.1 on 2018-10-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20181009_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='team_score',
            field=models.TextField(null=True),
        ),
    ]
