# Generated by Django 2.1 on 2018-09-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('title', models.TextField(null=True)),
                ('message', models.TextField()),
                ('files', models.FileField(blank=True, upload_to='files')),
            ],
            options={
                'ordering': ['-close_time'],
            },
        ),
    ]
