# Generated by Django 2.1 on 2018-09-28 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('file1', models.FileField(blank=True, upload_to='submissions')),
                ('file2', models.FileField(blank=True, upload_to='submissions')),
                ('file3', models.FileField(blank=True, upload_to='submissions')),
                ('file4', models.FileField(blank=True, upload_to='submissions')),
                ('file5', models.FileField(blank=True, upload_to='submissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
