# Generated by Django 2.1 on 2018-09-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
