# Generated by Django 2.1 on 2018-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20180930_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='message',
            field=models.TextField(),
        ),
    ]
